# Generated by Django 4.0 on 2023-12-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryarea_cost_deliverycost_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='add',
            field=models.TextField(blank=True, null=True),
        ),
    ]
