# Generated by Django 4.0 on 2023-12-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accountparent_remove_accountkeys_f_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalref',
            name='e_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
