# Generated by Django 4.0 on 2023-12-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='item_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
