# Generated by Django 4.0 on 2023-12-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_accountledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountledger',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
