# Generated by Django 4.0 on 2023-12-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_accountledger_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCOGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice', models.CharField(blank=True, max_length=50, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('direct', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('indirect', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
