# Generated by Django 4.0 on 2023-12-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeedetail_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='urname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
