# Generated by Django 4.0 on 2023-12-03 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeedetail_urname'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpolySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('deducte', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('sal_adv', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeedetail')),
            ],
        ),
    ]
