# Generated by Django 4.0 on 2023-12-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_empolyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='empolyrequest',
            name='d_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empolyrequest',
            name='d_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empolyrequest',
            name='vctn',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
