# Generated by Django 4.0 on 2023-12-03 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employee', '0006_empolyrequest_d_from_empolyrequest_d_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='owner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='empolyrequest',
            name='request_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='auth.user'),
        ),
    ]
