# Generated by Django 4.0 on 2023-12-18 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employeedetail_owner_alter_empolyrequest_request_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpolyAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('install', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('period', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('Remaining', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeedetail')),
            ],
        ),
    ]
