# Generated by Django 4.0 on 2023-12-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_empolyadvance'),
    ]

    operations = [
        migrations.AddField(
            model_name='empolyadvance',
            name='status',
            field=models.CharField(blank=True, default='PENDING', max_length=50, null=True),
        ),
    ]
