# Generated by Django 4.0 on 2023-12-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_empolyadvance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('install', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('advnce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.empolyadvance')),
            ],
        ),
    ]
