# Generated by Django 4.0 on 2023-12-19 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorytask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytask',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
