# Generated by Django 4.0 on 2023-12-20 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorytask_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=100, null=True)),
                ('msg', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, default='PENDING', max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.rawproducts')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryPOSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorypo')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.rawproducts')),
            ],
        ),
    ]
