# Generated by Django 4.0 on 2023-12-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventorypo_inventoryposub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorypo',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='inventorypo',
            name='product',
        ),
    ]
