# Generated by Django 4.0 on 2023-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_inventorypo_msg_remove_inventorypo_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryposub',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
