# Generated by Django 4.0 on 2023-12-13 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('vip', models.BooleanField(blank=True, default=False, null=True)),
                ('famly', models.BooleanField(blank=True, default=False, null=True)),
                ('area_ds', models.BooleanField(blank=True, default=False, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('addres_0', models.TextField(blank=True, null=True)),
                ('addres_1', models.TextField(blank=True, null=True)),
                ('addres_2', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mail', models.CharField(blank=True, max_length=150, null=True)),
                ('know_us', models.CharField(blank=True, max_length=150, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('i_date', models.DateField(blank=True, null=True)),
                ('vip', models.BooleanField(blank=True, default=False, null=True)),
                ('famly', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('direct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customerdirectory')),
            ],
        ),
    ]
