# Generated by Django 4.0 on 2023-12-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdiscount',
            name='flat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customerdiscount',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
