# Generated by Django 4.0 on 2023-12-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customerdiscount_flat_customerdiscount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdiscount',
            name='direct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customerdirectory'),
        ),
    ]
