# Generated by Django 4.0 on 2023-12-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customerdiscount_direct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdiscount',
            name='new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
