# Generated by Django 4.0 on 2023-12-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customerdiscount_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdiscount',
            name='site',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
