# Generated by Django 4.0 on 2023-12-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_customerdiscount_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='uuid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
