# Generated by Django 4.0 on 2023-12-05 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitcheninventory',
            name='vrb_cost',
        ),
        migrations.AddField(
            model_name='kitcheninventory',
            name='ingred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.ingredients'),
        ),
    ]
