# Generated by Django 4.0 on 2023-12-06 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_avg_price'),
        ('employee', '0007_employeedetail_owner_alter_empolyrequest_request_by'),
        ('kitchen', '0002_remove_kitcheninventory_vrb_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchenjobsassign',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='kitchenjobsassign',
            name='emply',
        ),
        migrations.RemoveField(
            model_name='kitchenjobsassign',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='kitchenjobsassign',
            name='j_end',
        ),
        migrations.RemoveField(
            model_name='kitchenjobsassign',
            name='j_stat',
        ),
        migrations.RemoveField(
            model_name='kitchenjobsassign',
            name='patch',
        ),
        migrations.RemoveField(
            model_name='kitchenjobsassign',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='kitchenjobsassign',
            name='start_time',
        ),
        migrations.CreateModel(
            name='SideKitchenInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('q_in', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('q_out', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('fnsh', models.BooleanField(blank=True, default=False, null=True)),
                ('p_return', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.kitcategory')),
                ('ingred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.ingredients')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.kitchenrecipe')),
            ],
        ),
        migrations.CreateModel(
            name='kitchenTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('j_stat', models.BooleanField(blank=True, default=False, null=True)),
                ('j_end', models.BooleanField(blank=True, default=False, null=True)),
                ('for_sale', models.BooleanField(blank=True, default=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('emply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeedetail')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenSubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('ingrd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.ingredients')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.kitchenjobsassign')),
                ('raw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.rawproducts')),
            ],
        ),
        migrations.AddField(
            model_name='kitchenjobsassign',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.kitchentask'),
        ),
    ]
