# Generated by Django 4.0 on 2023-12-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_remove_kitchenjobsassign_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenjobsassign',
            name='for_sale',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
