# Generated by Django 4.0 on 2023-12-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorytask'),
        ('kitchen', '0004_kitchenjobsassign_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchensubtask',
            name='ingrd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.kitcheninventory'),
        ),
        migrations.AlterField(
            model_name='kitchensubtask',
            name='raw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
    ]
