# Generated by Django 4.0 on 2023-12-08 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_recipeprice_recipefeatuers_featuersprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipeprice',
            name='extra_flat',
        ),
        migrations.RemoveField(
            model_name='recipeprice',
            name='extra_perc',
        ),
        migrations.RemoveField(
            model_name='recipeprice',
            name='point',
        ),
        migrations.AddField(
            model_name='recipeprice',
            name='feature',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='recipeprice',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.pricingsystem'),
        ),
    ]
