# Generated by Django 4.0 on 2023-12-08 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorytask'),
        ('kitchen', '0007_pricingsystem_remove_recipeprice_extra_flat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipefeatuers',
            name='raw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.rawproducts'),
        ),
    ]
