# Generated by Django 4.0 on 2023-12-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_alter_recipefeatuers_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuersprice',
            name='pause',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='recipeprice',
            name='pause',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
