# Generated by Django 4.0 on 2023-12-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0010_kitchenrecipe_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenjobsassign',
            name='for_cart',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='kitchentask',
            name='for_cart',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
