# Generated by Django 4.0 on 2023-12-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitchen', '0010_kitchenrecipe_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('service', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('delivery', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('items', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='No Note', null=True)),
                ('coupon', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=250, null=True)),
                ('ref', models.CharField(blank=True, max_length=10, null=True)),
                ('big', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, default='CREATED', max_length=20, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, default='CREATED', max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.recipeprice')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='CartName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('pwd', models.CharField(blank=True, max_length=150, null=True)),
                ('flat', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('prcnt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('pricing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.pricingsystem')),
            ],
        ),
        migrations.CreateModel(
            name='CartInv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('p_return', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartname')),
                ('pricing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.recipeprice')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.kitchenrecipe')),
            ],
        ),
        migrations.CreateModel(
            name='CartCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('t_strt', models.DateTimeField(blank=True, null=True)),
                ('t_end', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartname')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartname'),
        ),
    ]
