# Generated by Django 4.0 on 2023-12-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartname',
            name='status',
            field=models.CharField(blank=True, default='PENDING', max_length=10, null=True),
        ),
    ]
