# Generated by Django 4.0 on 2023-12-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartinv_feat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
