# Generated by Django 4.0 on 2023-12-11 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartname'),
        ),
    ]
