# Generated by Django 4.0 on 2023-12-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='feat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
