# Generated by Django 4.0 on 2023-12-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cartproducts_feat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsubproducts',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
