# Generated by Django 4.0 on 2023-12-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cartsubproducts_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcash',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
