# Generated by Django 4.0 on 2023-12-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cartcash_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcash',
            name='amt_in',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartcash',
            name='amt_out',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
