# Generated by Django 4.0 on 2023-12-12 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employeedetail_owner_alter_empolyrequest_request_by'),
        ('cart', '0010_cartcash_amt_in_cartcash_amt_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('j_end', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('emply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeedetail')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartname')),
            ],
        ),
    ]
