# Generated by Django 4.0 on 2023-12-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_cartproducts_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartname',
            name='task',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
