# Generated by Django 4.0 on 2023-12-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_rename_coupon_cart_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartname',
            name='inv',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
