# Generated by Django 4.0 on 2023-12-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_cart_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartname',
            name='online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
