# Generated by Django 4.0 on 2023-12-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_cartname_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartname',
            name='b_pwd',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
