# Generated by Django 4.0 on 2023-12-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_cartname_b_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
