# Generated by Django 4.0 on 2023-12-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_cart_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcash',
            name='p_close',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cartcash',
            name='p_open',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='cartcash',
            name='rev',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
